#UTILIZAR IMAGEN DE JDK21
FROM eclipse-temurin:21-jdk-alpine

#CREAR DIRECTORIO PARA LA APLICACION
VOLUME /tmp

ARG JAR_FILE=target/APP-DOCKER-GRUPO24-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} app.jar

#EXPONER EL PUERTO QUE UTILIZA LA APLICACION
EXPOSE 8080

#EJECUTAR EL ARCHIVO JAR CUANDO INICIE EL CONTENEDOR
ENTRYPOINT ["java", "-jar", "/app.jar"]